### PR TITLE
Use pyproject.toml

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Comment by adamltyson** [comment]
@dstansby it seems unrelated, but do you know why a (seemingly random) subset of test runners are failing?

**Review by adamltyson — APPROVED** [review]

**Comment by adamltyson** [comment]
I've approved, but held off merging if you have an idea of how to fix the tests. If not, feel free to merge and it can be sorted in another PR.

**Comment by adamltyson** [comment]
I've approved, but held off merging if you have an idea of how to fix the tests. If not, feel free to merge and it can be sorted in another PR.

**Comment by dstansby** [comment]
Yeah, I haven't had a chance to work out what's going on here, and I think it's happening in some other repos on linux too (maybe brainreg??). I'll merge this, and we can tackle this in a separate PR/issue.

**Pull request merged**
