### PR TITLE
Layout changes and refactoring (new!) 

### PR DESCRIPTION
**Pull request by horsto**
- Continued to change layout a bit like discussed for the last PR 
    - Atlas dropdown stays active and allows user to switch atlases. 
    - The "Add region" and "Add track" buttons are back in their original place (inside the corresponding panel)
    - There are new pushbuttons that enable to toggle the visibility of segmentation method panels (at the moment only "Trace tracks" and "Segment regions", but possibly more in the future). TODO: Re-arrange this into its own panel and make this a drop down? Will make sense layout-wise if more segmentation methods are added) 
    - Changed "Export" back to "Save" (button label) 

- Code refactoring
    - Created "layout" folder to collect layout helpers, like disabling Napari buttons / overriding Napari functionality. TODO: It would be great to overwrite the Napari rotate/transpose buttons to something that follows the bg space conventions, i.e. when the user transposes the brain and coordinate system follow smoothly and the brain isn't suddenly upside down or 90 degree rotated. That still happens at the moment) 
    - Started to factor out code for segmentation panels in subfolder `segmentation_panels`. Region and Track segmentation are now in their own class (as `RegionSeg(QGroupBox)` and `TrackSeg(QGroupBox)` respectively) and can be called from the main widget. I only started with this and it is probably not the most elegant execution. But it serves the purpose of de-cluttering the main widget code and prepares for addition of more segmentation methods in the future. 
    -  Behavior for saved data: Methods `check_saved_region()` and `check_saved_track()` are called upon initialising new atlas or new brainreg. 
   - Switching data/atlasses should completely remove layers via `remove_layers()` and re-initialise label/track layers (`self.track_layers = []` and `self.label_layers = []`) - might need safety procedures, etc. 

I tested region and track tracing quite extensively. It seems to all work, including loading of previous data. However, the function called after pressing the button `Add surface points` in "Track tracing" seems to run forever ... 

Not done: 
- I still couldn't quite test the brainreg import
- There is a missing function in `segment.py`: `export_label_layers` ? 
- I threw out the function `reset_variables(self)` in `segment.py` for now. Needs to be re-integrated somehow. 

---
Screenshot 2020-09-01 at 09 56 04

### CODE REVIEW

**Comment by adamltyson** [comment]
Hey @horsto, looks good!

> There are new pushbuttons that enable to toggle the visibility of segmentation method panels

I really like this. I wonder if there is a way to make it obvious that clicking the button again will hide the panel? Or even better, it gets collapsed to a box of single-line height that just has the title of the segmentation method? It would be cool if users knew that their tracing hasn't disappeared (assuming the variables aren't reset when you collapse the panel?).

> Re-arrange this into its own panel and make this a drop down?

I don't know whether this makes sense or not. A drop-down would be less preferable to a single toggle button for each method. I suppose it depends how many methods there end up being? I'm planning for 4 (although these could get reduced into sub-methods):
* Track tracing
* manual region segmentation
* semi automatic region segmentation (click in the centre of an object)
* fully automatic region segmentation (threshold-based)
In the future we could envision additional standalone methods. Automated track tracing?

> Switching data/atlasses should completely remove layers via remove_layers() and re-initialise label/track layers (self.track_layers = [] and self.label_layers = []) - might need safety procedures, etc.

Agree. It could just be an "Are you sure?" pop up.

> I tested region and track tracing quite extensively. It seems to all work, including loading of previous data. However, the function called after pressing the button Add surface points in "Track tracing" seems to run forever ...

Which atlas were you using? I think this is probably pretty inefficient for high-resolution atlases. It could be improved.


> I still couldn't quite test the brainreg import

Can I help with this?


> There is a missing function in segment.py: export_label_layers ?

What do you mean?



A few other things: 
* The linting tests are failing. I've set up pre-commit hooks that should check all the formatting before committing. Running `pre-commit install` should set this up for you.
* All of the GUI tests are failing.They all seem to require user input, so they may just not be calling the correct method anymore.
* There are some things I fixed that have been "unfixed". I noticed that if you try to export to brainrender when you don't have any tracks traced, it crashes because `self.splines` isn't explicitly set to `None` in `self.initialise_track_tracing` anymore. 

I may not have too much time to spend on this in the next few days, but I'll see what I can do. I might see if others are up for testing it before we're too set on a specific project structure.

**Comment by adamltyson** [comment]
Also:
> TODO: It would be great to overwrite the Napari rotate/transpose buttons to something that follows the bg space conventions, i.e. when the user transposes the brain and coordinate system follow smoothly and the brain isn't suddenly upside down or 90 degree rotated. That still happens at the moment)

For this do you mean that they should transform the view to a "normal" neuroanatomic saggital/horizontal view? I like that idea!

**Comment by horsto** [comment]
Thanks for the comments, @adamltyson! 

> I really like this. I wonder if there is a way to make it obvious that clicking the button again will hide the panel? Or even better, it gets collapsed to a box of single-line height that just has the title of the segmentation method? It would be cool if users knew that their tracing hasn't disappeared (assuming the variables aren't reset when you collapse the panel?).
Yes, good point, I think these are two different things that both have "easy" and "tough" solutions. The css style of every button is adjustable, so together with toggling visibility (as done now), you can change aspects, like for example make things bold and change color when they are toggled to visible and vice versa. For the collapsing: Yes, I thought about that, and all the solution I found by mining stackoverflow, etc. were quite involved. The easiest seems to be to play with the `.maximumheight` (forgot the correct nomenclature), such that the maximum height is set to a minimum when folded and back to "normal" when unfolded. This should be doable, but the problem then is to know the exact height when unfolded. But again, this could be a layout constant and you just play with it until it is just right. I haven't played with this yet though. 

> I suppose it depends how many methods there end up being?
Yes, that's right. I think it could end up being its own block. But that takes up space. Or a layout that packages the buttons tighter so it just fits. 

> Can I help with this?
This would be great. I don't have a lot of time these days. I'd probably have a look at the test failures (will communicate with you on slack since its quicker) and play with the layout a bit more. 

> There are some things I fixed that have been "unfixed". 
Sorry about that. Need to check it or maybe you could help me? 

> For this do you mean that they should transform the view to a "normal" neuroanatomic saggital/horizontal view? I like that idea!
Yes exactly. For that I overwrote the normal rotation function for the rotation button in napari last time I played with the GUI and atlases. It is possible, but needs some thinking (what's the best way to standardise this interface / bg space conventions / etc.).

I think the best for moving forward might be that I have another look at the layout components and see what I can do in terms of buttons / layout collapse, etc. Could you help me with "fixing the unfixing" and testing the brainreg stuff?

**Comment by adamltyson** [comment]
> For the collapsing: Yes, I thought about that, and all the solution I found by mining stackoverflow, etc. were quite involved. The easiest seems to be to play with the .maximumheight (forgot the correct nomenclature), such that the maximum height is set to a minimum when folded and back to "normal" when unfolded. This should be doable, but the problem then is to know the exact height when unfolded.

I don't know if it would work, but could we have two panels, one full, and one smaller, "collapsed one", and just swap the visibility for each? I'm keen to not spend ages and ages on this kind of stuff, as I don't think most users are too bothered.

> I think the best for moving forward might be that I have another look at the layout components and see what I can do in terms of buttons / layout collapse, etc. Could you help me with "fixing the unfixing" and testing the brainreg stuff?

Sure, it might take me a little while though.

**Comment by horsto** [comment]
> I don't know if it would work, but could we have two panels, one full, and one smaller, "collapsed one", and just swap the visibility for each?

Yes, good point. But the thing about this collapsing (which I haven't thought about before) is that the user I think would expect the header (the title) of each section to be clickable, which it isn't unless you spend way more time on making that work. Like truly unfold-able section would require that kind of interaction with the box itself? 

>Sure, it might take me a little while though. 

Thanks, I will have some time this afternoon to check this point with the splines / export to brainrender

**Comment by horsto** [comment]
There are also "tabs" in PyQT, but cramping in the title might not work so well (limited space horizontally)
image

**Comment by adamltyson** [comment]
> Yes, good point. But the thing about this collapsing (which I haven't thought about before) is that the user I think would expect the header (the title) of each section to be clickable, which it isn't unless you spend way more time on making that work. Like truly unfold-able section would require that kind of interaction with the box itself?

Didn't think about this. Maybe we just stick to a single button, and the string/formatting could change depending on the functionality. 

The tabs look nice, but maybe complicated. Even if there's 10 segmentation methods, would individual buttons be such an issue? Especially if the user would normally only have one segmentation panel showing at a time.

**Comment by horsto** [comment]
> The tabs look nice, but maybe complicated. Even if there's 10 segmentation methods, would individual buttons be such an issue? Especially if the user would normally only have one segmentation panel showing at a time.

Yes, I am also on the side of buttons. Just wanted to throw in more alternatives to make sure we don't miss the golden solution. I'd prefer buttons and will play with the formatting as you suggest.

**Comment by horsto** [comment]
Note: I changed the `qtbot(qtbot)` pytest fixture to throw only warning instead of errors when encountering "Leaked widgets" (an error I do not quite understand). 

I adapted the GUI tests to take over new function / ... names. The `test_tracks` routine seems partly circular to me at the end (saving / loading the same data - is that intended?).

**Comment by adamltyson** [comment]
> Note: I changed the qtbot(qtbot) pytest fixture to throw only warning instead of errors when encountering "Leaked widgets" (an error I do not quite understand).

I'm not sure I fully understand it either. I'm assuming it's about widgets getting created, and then not being removed when napari closes.

Copying the napari test fixtures is only meant to be a short-term hack anyway so we can run the GUI tests. Honestly we don't have to have the same high standards for testing as the napari folks. This tool will have orders of magnitude fewer users, and they will be more forgiving of small issues. 

>  The test_tracks routine seems partly circular to me at the end (saving / loading the same data - is that intended?).

It's not ideal, but these tests aren't meant to be perfect. Not good practice, but I've found _any_ test to be way better than none. We can always improve them as we go along.

> (edit) Also omitted disabling Napari buttons for now - this runs into test errors. Need to check what's going on there.

Are the errors related to the napari test fixture, or something else? We can probably disable any tests that ensure that the napari viewer is fully functional (considering we're messing with it).

Again, thanks so much for working on this.

**Comment by horsto** [comment]
Screenshot 2020-09-02 at 13 59 40
Screenshot 2020-09-02 at 13 59 56

Separated the loading panel from the methods chooser panel. Added theme specific button styling. If more methods are added in the future, the styling can be edited by changing the spacing setting (`.setSpacing`) of the methods chooser panel. However, it should have enough space for 4 methods. 

Known bug: The styling of the buttons is not handled very elegantly and should ideally be more customisable. Moreover, if the theme is toggled within one session, the buttons "lag" behind, and only when activated / toggled once change color.

**Pull request merged**
