### PR TITLE
Layout changes and refactoring

### PR DESCRIPTION
**Pull request by horsto**
- Started to group layout relevant helpers in `layout`
- Changed layout and workflow 
   - Layout elements stay hidden until the user clicks on buttons
   - Atlas dropdown stays and just gets deactivated 
- Some code refactoring

### CODE REVIEW

**Comment by adamltyson** [comment]
Hey, I like the disabling of unneeded napari icons etc, and that the panels (regions, tracks etc.) aren't visible unless needed.

When loading an atlas on it's own (not a brainreg project folder), the dropdown box becomes locked, and a new atlas can't be added. I think the user needs to be able to load a new project without closing napari and reopening (this is still a work in progress though, I was having issues deleting layers from an old project).

When an existing project is loaded, the loading of existing tracks seems to be inconsistent. If it's an atlas project, the tracks are loaded, but the track interface isn't. If its a brainreg project, they don't seem to be loaded at all (I didn't test regions).

I think the "Export to folder" should go back to "Save". It's not really an export (the user isn't meant to do anything with these files, it's just to bring the viewer back to the same state if they restart at a later date).

Thinking out loud, but rather than the "add track" button loading up the track panel, do you think that the "add track" button should go back into the track panel, and then we could have a button for "load tracking interface" or similar? This could be used to toggle the panel on/off, and also possibly used to load existing data (rather than it all being loaded upon launch)?

Thanks for your input on this, it's super helpful.


N.B. If you wanted a brainreg directory to test, you could generate one by following [the tutorial](https://docs.brainglobe.info/brainreg/tutorial), but it may not work on your mac. If not, let me know and I can send you the results.

**Comment by horsto** [comment]
Great, thanks for your feedback. And I am sorry for messing up things - I was too naive about what the intended functionality should be in some parts. It would be very helpful to get a brainreg output for testing purposes. 

Agree with "Save" button.

Also agree with keeping `add track` and showing the interface separate - that's a good idea. I will try to integrate that. It would be very great if those sub-panels were "unfold-able" (for the lack of a better word).

**Comment by adamltyson** [comment]
> And I am sorry for messing up things - I was too naive about what the intended functionality should be in some parts

No problem. I'm still working out exactly what this tool should be. Going over it with you is really useful.

I like "un-foldable". Not sure how we do this, but I like the idea that the user can easily browse the different segmentation options, and try them out, without an explicit load button. I don't know if there is qt functionality for this, but maybe we could have two "forms" of each subpanel? One with a title and an "Expand" button, and one with a title, a "collapse" button, and all the other functionality? Clicking expand/collapse would toggle between these two views.


Off topic, but I'm envisaging adding two additional segmentation modes, which are sort-of implemented in `neuro`. There's a [semi-automated segmentation method](https://github.com/SainsburyWellcomeCentre/neuro/blob/master/neuro/segmentation/lesion_and_track_tools/lesion_and_track_estimation.py) (we've used it for segmenting fibre tracks) and [a fully automated segmentation method ](https://github.com/SainsburyWellcomeCentre/neuro/blob/master/neuro/segmentation/injection_finder/extraction.py) for e.g. segmenting very bright objects that don't require manual segmentation. I can also see more being added, so maybe it might be worth developing a `SegmentationMethod` class that we can reuse?

FYI - I'm doing some minor refactoring and adding tests in the `tests` branch, but none of this is in `segment.py` so we shouldn't get any conflicts.

**Comment by horsto** [comment]
Yes, I think a `SegmentationMethod` class makes sense that can be filled with more and more methods over time. Should be accessible through a dropdown somewhere? 
I will look into the "un-foldable" / ... options either tonight or tomorrow.

**Comment by adamltyson** [comment]
> Yes, I think a SegmentationMethod class makes sense that can be filled with more and more methods over time. Should be accessible through a dropdown somewhere?

Yep, I think maybe the ideal situation is that the viewer starts with no segmentation methods, and each one can be selected from the drop-down as and when needed. Once they're added to the viewer, they can be removed (in which case you would need to add them again), or just collapsed to hide them, while using another.

**Pull request closed without merging**
